### ISSUE TITLE
Domain not registered with Tiny Cloud.

### ISSUE THREAD

**Issue by Cyberlane** [pauloamgomes/contentful-tinymce-editor#2]
I have created an account on TinyCloud, added the API key, but when I try to use the editor I see this:

![image](https://user-images.githubusercontent.com/1614416/108426178-bcbbe700-723b-11eb-9e13-d9884be341bc.png)

I have tried adding the following domains:

* contentful.com
* app.contentful.com
* mywebsite.com

Nothing seems to be working... When using this extension, which domain is it expecting? 😀

**Comment by pauloamgomes** [comment]
Hey @Cyberlane !

Can you try with the below ones:

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/102261/108429626-86cd3180-7240-11eb-9317-1b7e949e05c6.png">

**Comment by Cyberlane** [comment]
Solved! It was your GitHub.io domain which was doing it, which feels strange since I thought the request was coming from the rendered page (Contentful editor).

Thanks for the quick reply! 😄
